### PR TITLE
fixes for shaping

### PR DESCRIPTION
**Pull request by dk**
Hi Moshe,

I think this patch produces the results I expect. Hope it makes sense :)

Dmitry

### CODE REVIEW

**Comment by mkamensky** [comment]
Thanks! I made some changes, will be grateful if you can test it again.

**Comment by dk** [comment]
Looks fine, thanks! While we at it, what's the proper way to run 'perl Makefile.PL'? I had to use the one from CPAN distro

**Comment by mkamensky** [comment]
What do you mean? You just run it

**Comment by dk** [comment]
It doesn't work if I just run it, it says this:

    "" is not exported by the ExtUtils::MakeMaker module
     "" is not exported by the ExtUtils::MakeMaker module
    Can't continue after import errors at Makefile.PL line 8.
    BEGIN failed--compilation aborted at Makefile.PL line 8.

and if I look in to the file there's this strange line

    use ExtUtils::MakeMaker ##{ $eumm_version ##};

that makes trouble

**Comment by mkamensky** [comment]
Sorry, forgot about this, it uses Dist::Zilla (http://dzil.org). I run `dzil build`, then I get a tarball and proceed as usual

**Comment by dk** [comment]
ah, ok. Thank you!

**Comment by dk** [comment]
Hi Moshe, I'd like to ask you to notify me when 2.10 is out, if possible. Thanks!

**Pull request merged**
